version: '3'

services:
  db:
    image: mariadb
    container_name: db
    volumes: ["./db:/var/lib/mysql"]
    ports:
      - 3307:3307
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    networks:
      - gldm_net
  node:
    image: node
    container_name: node
    working_dir: /var/www/html
    ports:
      - '4000:4000'
    volumes: ['./:/var/www/html']
    command: tail -F anything
    networks:
      - gldm_net
networks:
  gldm_net: